"""Configuration for the Buzz API sample.

Configuration is read from environment variables (12-factor style).  For local
development the variables may be placed in a ``.env`` file in the project root;
:func:`load_env` loads that file into ``os.environ`` without overwriting
variables already set in the real environment.

No third-party dependency is required — the ``.env`` parser is built in.
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional

# Logical field  ->  environment variable name.
ENV_VARS = {
    "server_url": "BUZZ_SERVER_URL",
    "contact_information": "BUZZ_CONTACT_INFORMATION",
    "application_information": "BUZZ_APPLICATION_INFORMATION",
    "oauth_user_id": "BUZZ_OAUTH_USER_ID",
    "oauth_kid": "BUZZ_OAUTH_KID",
    "private_key_path": "BUZZ_PRIVATE_KEY_PATH",
}

_REQUIRED = ["server_url", "oauth_user_id", "oauth_kid", "private_key_path"]


def default_env_path() -> str:
    """Path to the ``.env`` file in the project root (parent of this module)."""
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")


def load_env(path: Optional[str] = None) -> bool:
    """Load ``KEY=VALUE`` lines from a ``.env`` file into ``os.environ``.

    Existing environment variables are never overwritten, so the real
    environment always wins.  Returns ``True`` if a file was found and read.
    """
    path = path or default_env_path()
    if not os.path.isfile(path):
        return False
    with open(path, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    return True


def read_config(load_dotenv: bool = True) -> Dict[str, str]:
    """Read configuration from the environment (optionally loading ``.env`` first).

    :raises SystemExit: with a helpful message if required values are missing.
    """
    if load_dotenv:
        load_env()

    config = {field: os.environ.get(var, "") for field, var in ENV_VARS.items()}

    missing: List[str] = [ENV_VARS[f] for f in _REQUIRED if not config[f]]
    if missing:
        raise SystemExit(
            "Missing required configuration: " + ", ".join(missing) + "\n"
            "  Run setup:  python scripts/run_buzz_sample.py\n"
            "  or copy .env.example to .env and fill it in (see README.md)."
        )
    return config


def write_env(config: Dict[str, str], path: Optional[str] = None) -> str:
    """Write configuration to a ``.env`` file and return the path written."""
    path = path or default_env_path()
    lines = ["# Buzz API sample configuration — generated by setup.", "# Do not commit this file.", ""]
    for field, var in ENV_VARS.items():
        lines.append(f"{var}={config.get(field, '')}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path
